apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: micros
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: micros
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.8.2
          ports:
            - hostPort: 9100
              containerPort: 9100
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys