microservice:
  name: quiz
  namespace: micros
  replicas: 2

workload:
  image: javaoleg/micros-quiz:2024.0.0
  port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
  livenessDelay: 40
  readinessDelay: 40

env:
  SPRING_PROFILE: prod

waitForServices:
  messageBroker:
    host: message-broker.micros # <hostname>.<namespace>
    port: 5672
  database:
    host: database.micros # <hostname>.<namespace>
    port: 5432