apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
data:
  {{- $prometheus := $.Files.Get "conf/prometheus.yml" }}
  {{- if not $prometheus }}
  {{- fail "conf/prometheus.yml not found!" }}
  {{- end }}
  prometheus.yml: |
    {{- $prometheus | nindent 4 }}