apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: {{ .Values.microservice.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.microservice.name }}
  serviceName: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: micros
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Values.microservice.name }}
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: {{ .Values.workload.image }}
          args:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
          volumeMounts:
            - mountPath: '/etc/prometheus/prometheus.yml'
              name: metrics-config-volume
              readOnly: true
              subPath: prometheus.yml
            - mountPath: "/prometheus"
              name: metrics-data-volume
          ports:
            - containerPort: {{ .Values.workload.ports.container }}
      volumes:
        - name: metrics-config-volume
          configMap:
            name: {{ .Values.microservice.name }}
  volumeClaimTemplates:
    - metadata:
        name: metrics-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 256Mi