apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}-nodeport
  namespace: {{ .Values.microservice.namespace }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  ports:
    - port: {{ .Values.workload.ports.container }}
      targetPort:  {{ .Values.workload.ports.container }}
      nodePort:  {{ .Values.workload.ports.node }}