apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
data:
  tempo-local.yaml: |
    server:
      http_listen_port: {{ .Values.workload.ports.queryTraces }}

    distributor:
      receivers:
        zipkin:

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
