apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: {{ .Values.microservice.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.microservice.name }}
  serviceName: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: micros
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Values.microservice.name }}
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: {{ .Values.workload.image }}
          args: [ "-config.file=/etc/tempo.yaml" ]
          volumeMounts:
            - mountPath: '/etc/tempo.yaml'
              name: tracing-config-volume
              readOnly: true
              subPath: tempo-local.yaml
            - mountPath: "/tmp/tempo/blocks"  # Persistent storage path for Tempo data
              name: tracing-data-volume
          ports:
            - containerPort: {{ .Values.workload.ports.receiveTraces }}
            - containerPort: {{ .Values.workload.ports.queryTraces }}
      volumes:
        - name: tracing-config-volume
          configMap:
            name: {{ .Values.microservice.name }}
  volumeClaimTemplates:
    - metadata:
        name: tracing-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 256Mi