apiVersion: v1
kind: Service
metadata:
  name: observability-visualization
  namespace: micros
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: observability-visualization
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000