services:
  frontend:
    environment:
      SPRING_PROFILE: prod
    image: javaoleg/micros-frontend:2024.0.0
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost || exit 1" ]
      interval: 30s
      retries: 3
      start_period: 40s
      timeout: 10s
  gateway:
    environment:
      SPRING_PROFILE: prod
    image: javaoleg/micros-gateway:2024.0.0
  quiz:
    image: javaoleg/micros-quiz:2024.0.0
    environment:
      SPRING_PROFILE: prod
  gamification:
    image: javaoleg/micros-gamification:2024.0.0
    environment:
      SPRING_PROFILE: prod
  database:
    image: javaoleg/micros-database:2024.0.0
    volumes:
      - micros-postgres-db-vol:/var/lib/postgresql/data
  message-broker:
    image: javaoleg/micros-msg-broker:2024.0.0
    volumes:
      - micros-rabbitmq-vol:/var/lib/rabbitmq


volumes:
  # note: names are optional, but without explicit names Docker will prefix the volume with project name
  micros-postgres-db-vol:
    name: micros-postgres-db-vol
  micros-rabbitmq-vol:
    name: micros-rabbitmq-vol