apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: micros
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/instance: database
  type: ClusterIP