server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/quiz
  rabbitmq:
    host: localhost

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG