server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/quiz
    driverClassName: org.postgresql.Driver
    username: microsappuser
    password: microservices-database-pwd

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG