spring:
  datasource:
    url: jdbc:postgresql://micros-database:5432/quiz
  rabbitmq:
    host: micros-msg-broker

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG