apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}-config
  namespace: {{ .Values.microservice.namespace }}
data:
  SPRING_PROFILE: {{ .Values.env.SPRING_PROFILE | quote}}