apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: database
  serviceName: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: micros
        app.kubernetes.io/component: persistence
        app.kubernetes.io/instance: database
    spec:
      containers:
        - name: database
          image: javaoleg/micros-database:2024.0.0
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: database-secret
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi