server:
  port: 8080

spring:
  application:
    name: gateway

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    rabbit:
      enabled: false

# Uncomment the configuration below if you want to enable route matching logs
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace
