server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes: # Note that routes are not-merged from multiple Spring profiles, they are overridden
        - id: quiz
          uri: http://quiz:8080/
          predicates:
            - Path=/quiz/**
        - id: gamification
          uri: http://gamification:8080/
          predicates:
            - Path=/leaderboard/**
      default-filters:
        - name: Retry
          args:
            retries: 1
            methods: GET,POST

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    rabbit:
      enabled: false

# Uncomment the configuration below if you want to enable route matching logs
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace
