spring:
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://micros-quiz:8080/
          predicates:
            - Path=/quiz/**
        - id: gamification
          uri: http://micros-gamification:8080/
          predicates:
            - Path=/leaderboard/**