apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
data:
  {{- $datasource := $.Files.Get "conf/datasource.yml" }}
  {{- $dashboard := $.Files.Get "conf/dashboard.yml" }}
  {{- $logsTracesMetrics := $.Files.Get "conf/logs_traces_metrics.json" }}
  {{- if not $datasource }}
  {{- fail "conf/datasource.yml not found!" }}
  {{- end }}
  {{- if not $dashboard }}
  {{- fail "conf/dashboard.yml not found!" }}
  {{- end }}
  {{- if not $logsTracesMetrics }}
  {{- fail "conf/logs_traces_metrics.json not found!" }}
  {{- end }}
  datasource.yml: |
    {{- $datasource | nindent 4 }}
  dashboard.yml: |
    {{- $dashboard | nindent 4 }}
  logs_traces_metrics.json: |
    {{- $logsTracesMetrics | nindent 4 }}