apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: {{ .Values.microservice.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: micros
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Values.microservice.name }}
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: {{ .Values.workload.image }}
          volumeMounts:
            - mountPath: '/etc/grafana/provisioning/datasources/datasource.yml'
              name: observability-visualization-config-volume
              readOnly: true
              subPath: datasource.yml
            - mountPath: '/etc/grafana/provisioning/dashboards/dashboard.yml'
              name: observability-visualization-config-volume
              readOnly: true
              subPath: dashboard.yml
            - mountPath: '/etc/grafana/provisioning/dashboards/logs_traces_metrics.json'
              name: observability-visualization-config-volume
              readOnly: true
              subPath: logs_traces_metrics.json
          ports:
            - containerPort: {{ .Values.workload.ports.target }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}

      volumes:
        - name: observability-visualization-config-volume
          configMap:
            name: {{ .Values.microservice.name }}