apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  ports:
    - port: {{ .Values.workload.port }}
      targetPort: {{ .Values.workload.port }}
  selector:
    app.kubernetes.io/instance: {{ .Values.microservice.name }}
  type: ClusterIP