apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
# This role is for Prometheus which uses Kubernetes API for Service Discovery
metadata:
  namespace: micros
  name: metrics-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]