apiVersion: v1
kind: Service
metadata:
  name: metrics-nodeport
  namespace: micros
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: metrics
  ports:
    - port: 9090
      targetPort:  9090
      nodePort:  32090