apiVersion: v1
kind: Service
metadata:
  name: metrics
  namespace: micros
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/instance: metrics
  type: ClusterIP
  clusterIP: None