apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | quote }}
