apiVersion: v1
kind: Service
metadata:
  name: message-broker
  namespace: micros
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app.kubernetes.io/instance: message-broker
  type: ClusterIP