apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: {{ .Values.microservice.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.microservice.name }}
  serviceName: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: micros
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: {{ .Values.microservice.name }}
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: {{ .Values.workload.image }}
          args: [ "-config.file=/etc/loki/local-config.yaml" ]
          volumeMounts:
            - mountPath: "/data"  # Persistent storage path for Loki data
              name: log-data-volume
          ports:
            - containerPort: {{ .Values.workload.port }}
  volumeClaimTemplates:
    - metadata:
        name: log-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 512Mi