apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: micros
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000