apiVersion: v1
kind: Service
metadata:
  name: gamification
  namespace: micros
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: gamification
  type: ClusterIP