apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamification
  namespace: micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gamification
  template:
    metadata:
      labels:
        app.kubernetes.io/name: micros
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: gamification
    spec:
      containers:
        - name: gamification
          image: javaoleg/micros-gamification:2024.1.0
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: gamification-config
          livenessProbe:
            exec:
              command: [ "java", "-jar", "/usr/local/gamification/healthcheck.jar" ]
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            exec:
              command: [ "java", "-jar", "/usr/local/gamification/healthcheck.jar" ]
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3