apiVersion: v1
kind: Service
metadata:
  name: tracing
  namespace: micros
spec:
  ports:
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: query
      port: 3200
      targetPort: 3200
  selector:
    app.kubernetes.io/instance: tracing
  type: ClusterIP
  clusterIP: None