server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gamification
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/gamification
  rabbitmq:
    host: localhost

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG