spring:
  datasource:
    url: jdbc:postgresql://micros-database:5432/gamification
  r2dbc:
    url: r2dbc:postgresql://micros-database:5432/gamification
  rabbitmq:
    host: micros-msg-broker

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG