server:
  port: 8080

spring:
  application:
    name: gamification
  datasource:
    url: jdbc:postgresql://database:5432/gamification
    driverClassName: org.postgresql.Driver
    username: microsappuser
    password: microservices-database-pwd
  r2dbc:
    url: r2dbc:postgresql://database:5432/gamification
    username: microsappuser
    password: microservices-database-pwd
  liquibase:
    change-log: classpath:/liquibase/changelogs/changelog-master.xml
    drop-first: false
    enabled: true
  rabbitmq:
    host: message-broker

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,prometheus
  health:
    rabbit:
      enabled: false
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://tracing:9411/api/v2/spans

amqp:
  exchange:
    attempts: attempts.topic
  queue:
    gamification: gamification.queue