apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
data:
  fluent-bit.conf: |
    {{- $fluentbit := $.Files.Get "conf/fluent-bit.conf" }}
    {{- if not $fluentbit }}
    {{- fail "conf/fluent-bit.conf not found!" }}
    {{- end }}
    {{- $fluentbit | nindent 4 }}