apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
       # seconds
       flush       1
       # for FluentBit's own logging, not app logs
       log_level   info
    [INPUT]
       Name tail
       Path /var/log/containers/*.log
       Exclude_Path      /var/log/containers/log-forward_*.log
       multiline.parser docker, cri
       # the asterisk is tag expansion, which means it will be replaced with
       # the value with the absolute path of the monitored file.
       # Note that tail plugin supports this tag expansion 
       Tag kube.*
       Mem_Buf_Limit 5MB
       Skip_Long_Lines On
    [FILTER]
       Name kubernetes
       Match kube.*
       Kube_Tag_Prefix  kube.var.log.containers.
       # Merge_Log On
       # Keep_Log Off
       # K8S-Logging.Parser On
       # K8S-Logging.Exclude On
    [FILTER]
       Name       grep
       Match      kube.*
       Exclude    $kubernetes['labels']['app.kubernetes.io/instance'] log-storage
       Exclude    $kubernetes['labels']['app.kubernetes.io/instance'] log-forward
       Exclude    $kubernetes['labels']['app.kubernetes.io/instance'] observability-visualization
       Exclude    $kubernetes['labels']['app.kubernetes.io/name'] ingress-nginx
       Exclude    $kubernetes['namespace_name'] kube-system
    #[OUTPUT]
    #   Name   stdout
    #   Match  kube.*
    #   Format json    
    [OUTPUT]
       # for sending logs to local Loki instance
       name        loki
       # Match logs from the micros namespace
       match       kube.*
       host        log-storage
       port        3100
       labels      job=fluentbit