microservice:
  name: gamification
  namespace: micros
  replicas: 1

workload:
  image: javaoleg/micros-gamification:2024.0.0
  port: 8080
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
  livenessDelay: 40
  readinessDelay: 40

env:
  SPRING_PROFILE: prod