apiVersion: v1
kind: Service
metadata:
  name: log-storage
  namespace: micros
spec:
  ports:
    - port: 3100
      targetPort: 3100
  selector:
    app.kubernetes.io/instance: log-storage
  type: ClusterIP
  clusterIP: None